tailwind.config = {
        darkMode: "class",
        theme: {
          extend: {
            "colors": {
                    "on-secondary": "#2d3136",
                    "on-secondary-container": "#b2b5bc",
                    "on-tertiary": "#532200",
                    "on-primary-fixed-variant": "#004f53",
                    "surface-container-highest": "#303636",
                    "error": "#ffb4ab",
                    "on-tertiary-fixed": "#331200",
                    "tertiary-container": "#e2844a",
                    "on-error": "#690005",
                    "surface-container": "#1b2121",
                    "surface": "#0e1415",
                    "secondary-fixed": "#e0e2e9",
                    "primary": "#55d8e1",
                    "tertiary-fixed-dim": "#ffb68d",
                    "surface-variant": "#303636",
                    "inverse-surface": "#dee4e4",
                    "surface-tint": "#55d8e1",
                    "outline": "#869394",
                    "on-primary": "#003739",
                    "on-secondary-fixed-variant": "#43474d",
                    "secondary": "#c3c6cd",
                    "on-primary-fixed": "#002022",
                    "background": "#0e1415",
                    "secondary-container": "#43474d",
                    "on-background": "#dee4e4",
                    "on-surface": "#dee4e4",
                    "on-surface-variant": "#bbc9ca",
                    "surface-container-low": "#171d1d",
                    "primary-container": "#00adb5",
                    "surface-container-lowest": "#090f10",
                    "secondary-fixed-dim": "#c3c6cd",
                    "on-tertiary-fixed-variant": "#763300",
                    "on-error-container": "#ffdad6",
                    "inverse-primary": "#00696e",
                    "tertiary": "#ffb68d",
                    "primary-fixed-dim": "#55d8e1",
                    "surface-container-high": "#252b2b",
                    "inverse-on-surface": "#2b3132",
                    "on-secondary-fixed": "#181c21",
                    "outline-variant": "#3c494a",
                    "tertiary-fixed": "#ffdbc9",
                    "surface-dim": "#0e1415",
                    "on-tertiary-container": "#582500",
                    "error-container": "#93000a",
                    "surface-bright": "#343a3b",
                    "primary-fixed": "#75f5fd",
                    "on-primary-container": "#003a3d"
            },
            "borderRadius": {
                    "DEFAULT": "0.125rem",
                    "lg": "0.25rem",
                    "xl": "0.5rem",
                    "full": "0.75rem"
            },
            "spacing": {
                    "base_unit": "4px",
                    "sidebar_width": "300px",
                    "gutter": "24px",
                    "container_padding": "20px",
                    "margin_page": "32px"
            },
            "fontFamily": {
                    "headline-xl-mobile": ["Inter"],
                    "headline-lg": ["Inter"],
                    "label-sm": ["Inter"],
                    "label-md": ["Inter"],
                    "body-md": ["Open Sans"],
                    "headline-xl": ["Inter"],
                    "headline-md": ["Inter"],
                    "body-lg": ["Open Sans"]
            },
            "fontSize": {
                    "headline-xl-mobile": ["26px", {"lineHeight": "32px", "fontWeight": "700"}],
                    "headline-lg": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
                    "label-sm": ["11px", {"lineHeight": "14px", "fontWeight": "500"}],
                    "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
                    "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
                    "headline-xl": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                    "headline-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
                    "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
            }
          },
        },
      }
